// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using finanzas_backend.Data;

#nullable disable

namespace finanzas_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260715052512_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.CategoriaGasto", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCategoria"));

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCategoria");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Categoria_Gasto");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Credito", b =>
                {
                    b.Property<int>("IdCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_credito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCredito"));

                    b.Property<string>("Entidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("entidad");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdCredito");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Credito");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.CupoCredito", b =>
                {
                    b.Property<int>("IdCupoCredito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cupo_credito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCupoCredito"));

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdCredito")
                        .HasColumnType("integer")
                        .HasColumnName("id_credito");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdCupoCredito");

                    b.HasIndex("IdCredito");

                    b.ToTable("Cupo_Credito");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.DetalleCuotas", b =>
                {
                    b.Property<int>("IdDetalleCuotas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cuotas");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleCuotas"));

                    b.Property<int>("CantidadCuotas")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_cuotas");

                    b.Property<int>("CuotasPagadas")
                        .HasColumnType("integer")
                        .HasColumnName("cuotas_pagadas");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_compra");

                    b.Property<DateTime?>("FechaUltimaCuota")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_ultima_cuota");

                    b.Property<decimal>("MontoCuota")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_cuota");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_total");

                    b.Property<bool>("PagadaCompletamente")
                        .HasColumnType("boolean")
                        .HasColumnName("pagada_completamente");

                    b.HasKey("IdDetalleCuotas");

                    b.ToTable("Detalle_Cuotas");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Deuda", b =>
                {
                    b.Property<int>("IdDeuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_deuda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDeuda"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("MontoOriginal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_original");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("SaldoActual")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("saldo_actual");

                    b.Property<decimal?>("TasaInteres")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("tasa_interes");

                    b.HasKey("IdDeuda");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Deudas");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.MetodoPago", b =>
                {
                    b.Property<int>("IdMetodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_metodo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMetodo"));

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdMetodo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Metodo_Pago");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.PagoSubscripcion", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pago");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPago"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fechaInicio");

                    b.Property<int>("IdSubscripcion")
                        .HasColumnType("integer")
                        .HasColumnName("id_subscripcion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Mes")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("mes");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdPago");

                    b.HasIndex("IdSubscripcion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Pago_Subscripcion");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Presupuesto", b =>
                {
                    b.Property<int>("IdPresupuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_presupuesto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresupuesto"));

                    b.Property<int>("Anio")
                        .HasColumnType("integer")
                        .HasColumnName("anio");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdPresupuesto");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Presupuesto");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.PresupuestoItem", b =>
                {
                    b.Property<int>("IdPresupuestoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_presupuesto_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPresupuestoItem"));

                    b.Property<int?>("IdCategoriaGasto")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_gasto");

                    b.Property<int>("IdPresupuesto")
                        .HasColumnType("integer")
                        .HasColumnName("id_presupuesto");

                    b.Property<int?>("IdTipoGasto")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_gasto");

                    b.Property<decimal>("MontoObjetivo")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_objetivo");

                    b.Property<decimal>("MontoReal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto_real");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_item");

                    b.HasKey("IdPresupuestoItem");

                    b.HasIndex("IdCategoriaGasto");

                    b.HasIndex("IdPresupuesto");

                    b.HasIndex("IdTipoGasto");

                    b.ToTable("Presupuesto_Item");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.SoporteFactura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("Direccion")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("direccion");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_subida");

                    b.Property<int?>("IdTransaccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_transaccion");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("nombre_archivo");

                    b.Property<bool>("ProcesadoIa")
                        .HasColumnType("boolean")
                        .HasColumnName("procesado_ia");

                    b.Property<int>("TamanoBytes")
                        .HasColumnType("integer")
                        .HasColumnName("tamano_bytes");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_mime");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdTransaccion")
                        .IsUnique();

                    b.ToTable("SoporteFactura");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Subscripcion", b =>
                {
                    b.Property<int>("IdSubscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_subscripcion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSubscripcion"));

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("precio");

                    b.HasKey("IdSubscripcion");

                    b.ToTable("Subscripcion");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.TipoGasto", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipo"));

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Tipo_Gasto");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.TipoTransaccion", b =>
                {
                    b.Property<int>("IdTipoTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_transaccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTipoTransaccion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdTipoTransaccion");

                    b.ToTable("Tipo_Transaccion");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Transaccion", b =>
                {
                    b.Property<int>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_transaccion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTransaccion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int?>("IdCategoriaGasto")
                        .HasColumnType("integer")
                        .HasColumnName("id_categoria_gasto");

                    b.Property<int?>("IdCredito")
                        .HasColumnType("integer")
                        .HasColumnName("id_credito");

                    b.Property<int?>("IdDetalleCuotas")
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cuotas");

                    b.Property<int?>("IdDeuda")
                        .HasColumnType("integer")
                        .HasColumnName("id_deuda");

                    b.Property<int>("IdMetodoPago")
                        .HasColumnType("integer")
                        .HasColumnName("id_metodo_pago");

                    b.Property<int?>("IdTipoGasto")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_gasto");

                    b.Property<int>("IdTipoTransaccion")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_transaccion");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("monto");

                    b.HasKey("IdTransaccion");

                    b.HasIndex("IdCategoriaGasto");

                    b.HasIndex("IdCredito");

                    b.HasIndex("IdDetalleCuotas");

                    b.HasIndex("IdDeuda");

                    b.HasIndex("IdMetodoPago");

                    b.HasIndex("IdTipoGasto");

                    b.HasIndex("IdTipoTransaccion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Transaccion");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("correo");

                    b.Property<bool>("Estado")
                        .HasColumnType("boolean")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nombre_usuario");

                    b.Property<string>("UidAuth")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("uid_auth");

                    b.HasKey("IdUsuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.CategoriaGasto", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Usuario", "Usuario")
                        .WithMany("CategoriasGasto")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Credito", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Usuario", "Usuario")
                        .WithMany("Creditos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.CupoCredito", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Credito", "Credito")
                        .WithMany("CuposCredito")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credito");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Deuda", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Usuario", "Usuario")
                        .WithMany("Deudas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.MetodoPago", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Usuario", "Usuario")
                        .WithMany("MetodosPago")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.PagoSubscripcion", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Subscripcion", "Subscripcion")
                        .WithMany("PagosSubscripcion")
                        .HasForeignKey("IdSubscripcion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("finanzas_backend.Infrastructure.Models.Usuario", "Usuario")
                        .WithMany("PagosSubscripcion")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Subscripcion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Presupuesto", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Usuario", "Usuario")
                        .WithMany("Presupuestos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.PresupuestoItem", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.CategoriaGasto", "CategoriaGasto")
                        .WithMany("PresupuestosItems")
                        .HasForeignKey("IdCategoriaGasto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("finanzas_backend.Infrastructure.Models.Presupuesto", "Presupuesto")
                        .WithMany("Items")
                        .HasForeignKey("IdPresupuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("finanzas_backend.Infrastructure.Models.TipoGasto", "TipoGasto")
                        .WithMany("PresupuestosItems")
                        .HasForeignKey("IdTipoGasto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CategoriaGasto");

                    b.Navigation("Presupuesto");

                    b.Navigation("TipoGasto");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.SoporteFactura", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Transaccion", "Transaccion")
                        .WithOne("SoporteFactura")
                        .HasForeignKey("finanzas_backend.Infrastructure.Models.SoporteFactura", "IdTransaccion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.TipoGasto", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.Usuario", "Usuario")
                        .WithMany("TiposGasto")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Transaccion", b =>
                {
                    b.HasOne("finanzas_backend.Infrastructure.Models.CategoriaGasto", "CategoriaGasto")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdCategoriaGasto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("finanzas_backend.Infrastructure.Models.Credito", "Credito")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdCredito")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("finanzas_backend.Infrastructure.Models.DetalleCuotas", "DetalleCuotas")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdDetalleCuotas")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("finanzas_backend.Infrastructure.Models.Deuda", "Deuda")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdDeuda")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("finanzas_backend.Infrastructure.Models.MetodoPago", "MetodoPago")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdMetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("finanzas_backend.Infrastructure.Models.TipoGasto", "TipoGasto")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdTipoGasto")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("finanzas_backend.Infrastructure.Models.TipoTransaccion", "TipoTransaccion")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdTipoTransaccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("finanzas_backend.Infrastructure.Models.Usuario", "Usuario")
                        .WithMany("Transacciones")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CategoriaGasto");

                    b.Navigation("Credito");

                    b.Navigation("DetalleCuotas");

                    b.Navigation("Deuda");

                    b.Navigation("MetodoPago");

                    b.Navigation("TipoGasto");

                    b.Navigation("TipoTransaccion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.CategoriaGasto", b =>
                {
                    b.Navigation("PresupuestosItems");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Credito", b =>
                {
                    b.Navigation("CuposCredito");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.DetalleCuotas", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Deuda", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.MetodoPago", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Presupuesto", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Subscripcion", b =>
                {
                    b.Navigation("PagosSubscripcion");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.TipoGasto", b =>
                {
                    b.Navigation("PresupuestosItems");

                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.TipoTransaccion", b =>
                {
                    b.Navigation("Transacciones");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Transaccion", b =>
                {
                    b.Navigation("SoporteFactura");
                });

            modelBuilder.Entity("finanzas_backend.Infrastructure.Models.Usuario", b =>
                {
                    b.Navigation("CategoriasGasto");

                    b.Navigation("Creditos");

                    b.Navigation("Deudas");

                    b.Navigation("MetodosPago");

                    b.Navigation("PagosSubscripcion");

                    b.Navigation("Presupuestos");

                    b.Navigation("TiposGasto");

                    b.Navigation("Transacciones");
                });
#pragma warning restore 612, 618
        }
    }
}
